services:
  backend:
    build: .
    container_name: wolf-ovrn-backend
    restart: always
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
      - SPRING_PROFILES_ACTIVE=prod