spring:
  application:
    name: wolf-ovrn-backend

  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
             # - openid
              - email
              - profile

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  frontend:
    redirect-url: ${FRONTEND_REDIRECT_URL:http://localhost:3000/}
  cookie:
    secure: ${COOKIE_SECURE:false}
    domain: ${COOKIE_DOMAIN:}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.transaction: DEBUG
    org.springframework.transaction: TRACE
    org.springframework.web: DEBUG
    jakarta.validation: DEBUG


---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
